Разметка главной страницы мобильной версии
htmlacademy-adaptive/1705973-pink-22 pull request #2
Opened 2021-03-28 05:31 UTC by Belladonna26

2021-03-28 14:28 UTC, mikhailmaclay requested changes
Пока что увидел довольно простую, не усложненную будущими классами разметку, это окей, но не стесняйся усложнять через создание новых блоков. В некоторых моментах замечания подразумевают повторное ревью, поэтому в одну попытку не уложимся

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +            </p>
Однотипно форматируй разметку, пожалуйста. Если судить по прошлым элементам, закрывающий тег должен быть после текста без переноса на следующую строку

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <img src="img/iphone-basic.png" width="157" height="320" alt="Iphone 7">
Это декоративное изображение, в разметке его не должно быть

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +    <section class="reviews">
Придирка: Правильней будет назвать `testimonials`, так как `reviews `подразумевает очень подробный отзыв об опыте использования приложения

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <h2 class="visually-hidden">Отзывы о приложении</h2>
Положи его в первом уровне вложенности этой секции. Нет смысла его вкладывать глубоко, если визуально он все равно скрыт

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <div class="reviews__list slider__list">
Что за дублирующая иерархия нарисовалась? Это либо одно, либо другое

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <p class="reviews__toggles slider__toggles">
`...__controls`

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +            <div class="reviews__author-info">
У тебя этот класс используется и как обертка над `Николай Петров` и `25 лет, водитель трамвая` и как для `25 лет, водитель трамвая`. Правильней будет тогда  поправить имя класса для общей обертки - ` reviews__author`

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +      <div class="container slider">
Ты вот эти истории с `slider` давай выпиливай

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <p class="sub__toggles slider__toggles">
[98](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/2/files#diff-2d7f1f1674143252d45bafff792f025edb37f384958f37ae50cfdf3ddeb03c7eR98)

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <p class="reviews__toggles slider__toggles">
Добавь еще `aria-label`, отвечающие на вопрос "Что будет если нажму?"

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +    <div class="sub">
Можно сделать `section`

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +    <div class="sub">
Не хватает скрытого заголовка секции

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <h2 class="visually-hidden">Наши контакты</h2>
[87](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/2/files#diff-2d7f1f1674143252d45bafff792f025edb37f384958f37ae50cfdf3ddeb03c7eR87)

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <p class="contacts__subtitle">Остались вопросы?<br>
Использование `br` здесь это актуальный вопрос. На макете выглядит так, будто можно обойтись и без него

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <div class="contacts__info">
Просто `info` это слишком абстрактно. Конкретно это способы связи

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +          <div class="contacts__info-phone">
Нет никакого смысла в названии класса отражать способ связи, стили-то одинаковые

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +      <iframe
Не забудь сразу подчистить то что забраковали в прошлый раз на проверке в `iframe`

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +        <img src="img/logo/footer-logo/logo-mob-footer.svg" width="145" height="40" alt="Логотип приложения">
[12](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/2/files#diff-2d7f1f1674143252d45bafff792f025edb37f384958f37ae50cfdf3ddeb03c7eR12)

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +            <img src="img/html-academy-footer.svg" width="27" height="34" alt="Логотип html academy">
Вай, вай, вай. Как не уважительно писать  HTML Academy с маленькой буквы

2021-03-28 14:28 UTC, mikhailmaclay commented on source/index.html
> +          <a class="copyright__logo" href="https://htmlacademy.ru/intensive/adaptive" aria-label="Ссылка на html Academy">
HTML Academy

2021-03-28 14:29 UTC, mikhailmaclay commented on source/index.html
> +    <a class="page-header__logo">
Или ты тут хотела `page__header-logo`?

2021-03-28 18:24 UTC, Belladonna26 commented on source/index.html
> +    <h1 class="visually-hidden">Pink - приложение, которое изменит твою жизнь!</h1>
Ну да, как бы резюмируя исходя из концепции приложения, описанной на сайте

2021-03-28 18:25 UTC, Belladonna26 commented on source/index.html
> +        <p class="app__slogan">Взгляните на жизнь иначе!</p>
если что slogan переводится также как девиз или лозунг)

2021-03-28 18:43 UTC, mikhailmaclay commented on source/index.html
> +        <p class="app__slogan">Взгляните на жизнь иначе!</p>
А, окей

2021-03-28 18:45 UTC, mikhailmaclay commented on source/index.html
> +    <h1 class="visually-hidden">Pink - приложение, которое изменит твою жизнь!</h1>
А почему ты решила запихнуть `h1` в `main`?

2021-03-28 18:46 UTC, mikhailmaclay commented on source/index.html
> +    <h1 class="visually-hidden">Pink - приложение, которое изменит твою жизнь!</h1>
Лично мне кажется что заголовок первого уровня должен отвечать на вопросы "Что за сайт?" и "Что за страница?". Как сама думаешь?

2021-03-29 08:51 UTC, Belladonna26 commented on source/index.html
> +    <h1 class="visually-hidden">Pink - приложение, которое изменит твою жизнь!</h1>
еще до прочитки твоего коммента поменяла этот момент и так) перенесла в body h1, текст немного изменю у заголовка, чтобы конкретнее отображал суть страницы

2021-03-29 10:31 UTC, Belladonna26 commented on source/index.html
> +        <div class="contacts__info">
если конкретно называть способ связи,получаются очень длинные названия типа way-of-communication; communication-type и т.п
contacts-type разве что

2021-03-29 10:35 UTC, Belladonna26 commented on source/index.html
> +      <iframe
я не припоминаю, что в iframe у меня к чему то придирались

2021-03-29 19:46 UTC, mikhailmaclay commented on source/index.html
> +      <iframe
Да, это было у другого студента. Автоматическая проверка придралась к `allowfullscreen="false"` и `width="100%"`

2021-03-29 19:47 UTC, mikhailmaclay commented on source/index.html
> +    <h1 class="visually-hidden">Pink - приложение, которое изменит твою жизнь!</h1>
Было бы здорово, если бы я проверял актуальный код и не тратил свое время на то, что ты уже исправила. А также, было бы здорово, если бы я помечал обсуждение как разрешенное

2021-03-29 19:49 UTC, mikhailmaclay commented on source/index.html
> +        <div class="contacts__info">
Да, лучше проявлять воображение, а не идти в лом как с `way-of-communication`

2021-03-30 20:46 UTC, mikhailmaclay requested changes

2021-03-30 20:46 UTC, mikhailmaclay commented on source/index.html
> +      <h2 class="visually-hidden">Пользовательская навигация</h2>
Так обозвать можно только в этом случае, так как навигация одна на странице. Если бы была еще, это был бы повод разнообразить именование

2021-03-30 20:46 UTC, mikhailmaclay commented on source/index.html
> +            </p>
Все еще не решено

2021-03-30 20:46 UTC, mikhailmaclay commented on source/index.html
> +        <div class="page__footer-copyright copyright">
`page__footer-copyright` выглядит уже слишком жирно. Давай сделаем блок `page-footer`

2021-03-30 20:46 UTC, mikhailmaclay commented on source/index.html
> +              <img src="img/youtube.svg" width="15" height="13" alt="Логотип You Tube">
YouTube

2021-03-30 20:46 UTC, mikhailmaclay commented on source/index.html
> +        <p class="sub__controls">
Тут `p` вообще не при делах. Посмотри, пожалуйста, для чего используют `p`

2021-03-30 20:46 UTC, mikhailmaclay commented on source/index.html
> +    <section class="testimonials">
Прикольно что ты переименовала в testimonials

2021-03-30 20:46 UTC, mikhailmaclay commented on source/index.html
> +              <p class="testimonials__author-info">25 лет, водитель трамвая</p>
Придирка: Тут можно и `span` обойтись

2021-03-30 21:00 UTC, mikhailmaclay commented on source/img/logo/footer-logo/logo-mob-footer.svg
> +</svg>
Придирка: `logo-colored-mobile`

2021-03-30 21:00 UTC, mikhailmaclay commented on source/img/logo/footer-logo/logo-desk-footer.svg
> +</svg>
Придирка: `logo-colored-desktop`

2021-03-30 21:00 UTC, mikhailmaclay commented on source/img/logo/logotype-desktop.svg
> +</svg>
Придирка: `logo-desktop`

2021-03-30 21:00 UTC, mikhailmaclay commented on source/img/close-btn.svg
> +</svg>
Ну это ж не кнопка

2021-03-31 08:54 UTC, Belladonna26 commented on source/index.html
> +            </p>
я исправляла, в конце форматирую код горячими клавишами и он сносит закрывающий тег на новую строку именно у этого абзаца
буду вручную чекать потом

2021-04-01 15:03 UTC, mikhailmaclay approved these changes

2021-04-01 15:03 UTC, merged