Разметка страницы с фотографиями
htmlacademy-adaptive/1705973-pink-22 pull request #4
Opened 2021-03-30 14:30 UTC by Belladonna26

2021-04-04 12:40 UTC, mikhailmaclay requested changes
Неплохо, но есть вопросы и недочеты, которые нужно исправить. Те замечания, что по странице формы, исправь, пожалуйста, в пулреквесте про страницу формы

2021-04-04 12:40 UTC, mikhailmaclay commented on source/form.html
> +        <textarea name="review" id="review-field"> Можно прям в красках, не стесняясь в выражениях</textarea>
Лишний пробельчик в начале строки

2021-04-04 12:40 UTC, mikhailmaclay commented on source/form.html
> +        <input class="button" type="submit" value="Отправить форму">
Забудь про `input type="submit"`, используй `button` если кнопка обернута в форму или с атрибутами `type="submit" и form="form-id-attr-value"`, если вне формы

2021-04-04 12:40 UTC, mikhailmaclay commented on source/form.html
> +  </footer>
Перетащи изменения футера с главной страницы

2021-04-04 12:40 UTC, mikhailmaclay commented on source/form.html
> +      <a class="page__footer-logo" href="https://htmlacademy.ru/intensive/adaptive">
Не указан `aria-label`

2021-04-04 12:40 UTC, mikhailmaclay commented on source/form.html
> +    <div class="modal__footer">
Здесь по идее без `modal__footer` должно быть. Посмотри на макете, футер есть только у модального окна успешной отправки заявки

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +  <title>HTML Academy: Пинк</title>
Такой заголовок прокатит для главной страницы, но здесь уже нужно дать пользователю понять где он находится

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +    <a class="page-header__logo" href="index.html">
Не указан `aria-label`

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +            <a class="main-navigation__link">Фотографии</a>
Забыла класс  `main-navigation__link_current`

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +            <a class="main-navigation__link main-navigation__link_current" href="form.html">Конкурс</a>
Убрать класс  `main-navigation__link_current`

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +    <h2 class="page-title">Фотографии пользователей</h2>
Прям отдельный блок `page-title`?

2021-04-04 12:40 UTC, mikhailmaclay commented on source/form.html
> +    <h1 class="page-title">Конкурс на самое безбашенное путешествие с Пинк</h1>
Прям отдельный блок `page-title`?

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +    <div class="page-main__wrapper">
А зачем здесь `wrapper`?

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +      <p class="page-main__text">Взгляните на фотографии, которые выкладывают пользователи! Видите, как не хватает ваших?</p>
Я бы не стал это содержимое ассоциировать с блоком `page-main`. Это больше похоже на вступительную часть ко всему блоку с фотографиями

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +      <blockquote class="newsfeed">
Использование `blockquote` лично для меня здесь спорно. Смотри, сущность - фото, а текст под фото это подпись автора. Мб попробовать `article`?

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +      <blockquote class="newsfeed">
Класс `newsfeed` тоже как-то не в тему, так как news feed это что-то общее, что содержит отдельные новости, а ты здесь именуешь этим классом именно новости

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#">
Не указан `aria-label`

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +            <button class="button-like" type="button"><img src="img/photos/heart.svg" width="13" height="12"
Не указан `aria-label`

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +      </blockquote>
Это все подкорректируй на основе замечаний по первому `newsfeed`

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +    <div class="page-main__wrapper">
Кажется что логичней название класса было бы связать с каталогом фотографий, `wrapper` слишком абстрактно, плюс принадлежность к `page-main`, кажется, излишня

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +      <p class="page-main__text">Затмите их всех!<br>
А вот это уже вступительная часть блока с загрузкой фото

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +    <section class="filter">
Все-таки кажется что на макете визуально отображен второй шаг формы загрузки фотографии. Сначала загружаем фото и добавляем подпись, потом обрабатываем его (как видно на макете). Как думаешь?

2021-04-04 12:40 UTC, mikhailmaclay commented on source/form.html
> +</body>
Забыла сверстать оверлей, который в макете называется Lock. Он блокирует клики по области вне модального окна, затемняет и обесцвечивает все что под ним

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +  </section>
Забыла удалить?

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +  </footer>
Переносим изменения футера с главной страницы

2021-04-04 12:40 UTC, mikhailmaclay commented on source/photos.html
> +      <a class="page__footer-logo" href="https://htmlacademy.ru/intensive/adaptive">
Не указал `aria-label`

2021-04-07 06:42 UTC, Belladonna26 commented on source/form.html
> +      <fieldset class="fieldset fieldset_background">
ну здесь пошла по принципу,что у двух филдсетов отличается только фоновый цвет, в лайвах как то говорили что лучше не привязываться в названии класса к конкретному цвету например, а так могла бы написать например fieldset_grey/fieldset_colored

2021-04-07 06:57 UTC, Belladonna26 commented on source/form.html
> +    <div class="modal__footer">
у неудачной отправки в десктопной версии появляется серый фон внизу, из-за него добавляла чтобы типа можно было прописать потом цвет

2021-04-07 07:07 UTC, Belladonna26 commented on source/form.html
> +</body>
Если ты имеешь ввиду Lock, принадлежащий к tablet и desktop, то это добавлено было, чтобы типа мы в первую очередь сосредоточены были только на верстке мобильной версии, а потом уже просто как время придет, разблокировали его и дальше начали доверстывать для таблетов и компа, но к верстке он не имеет отношения. А других Lock я не нашла

2021-04-07 08:31 UTC, Belladonna26 commented on source/photos.html
> +    <section class="filter">
как мне кажется сначала уж должна пройти обработка фото, а потом предложить придумать подпись к фото,хотя по факту особой разницы нет. И по сути на странице формы: там без фото, нужно рассказать о своей истории, чтобы поучаствовать в конкурсе, а на странице с фотками просто фотолента пользователей. Но в любом случае в ТЗ нет данных об этом, должны ли эти формы являться продолжением друг друга

2021-04-09 21:26 UTC, mikhailmaclay approved these changes
Не стану задерживать этот ПР, можно будет поправить в задании про стилизацию. Только не забудь потом в ПРе задания по стилизации добавить комментарии к строкам, которые ты добавила как исправление замечаний, со ссылкой на замечание в этом ПРе. И не забудь через интерфейс сдать задание

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +      <a class="page-header__logo" href="index.html" aria-label="Логотип Pink">
[214](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R214)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#" aria-label="Ссылка на полноразмерное изображение">
Лучше просто `Полноразмерное изображение`. Тогда это будет примерно так: -"Ссылка - Полноразмерное изображение". В твоем случае это "Ссылка - Ссылка на полноразмерное изображение"

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#" aria-label="Ссылка на полноразмерное изображение">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#" aria-label="Ссылка на полноразмерное изображение">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#" aria-label="Ссылка на полноразмерное изображение">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#" aria-label="Ссылка на полноразмерное изображение">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#" aria-label="Ссылка на полноразмерное изображение">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +          <cite class="photofeed__author">Анна</cite>
Думаешь стоит `cite` использовать?

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +          <cite class="photofeed__author">Левон</cite>
[66](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R66)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +          <cite class="photofeed__author">Антон</cite>
[66](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R66)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +          <cite class="photofeed__author">Борис</cite>
[66](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R66)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +          <cite class="photofeed__author">Сергей</cite>
[66](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R66)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +          <cite class="photofeed__author">Максим</cite>
[66](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R66)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +    <section class="filter">
Пока разметка блока не дотягивает до претендента на истину, Уверен, что тебе придется переписать это в следующих заданиях

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <img src="img/photos/winter.jpg" width="280" height="374" alt="Заснеженная дорога">
Придется стилизовать 100%. Не хватает класса

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        </div>
Пока верстай так и попинывай меня, чтобы я придумал как сделать лучше

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +          <!-- Исправить на button? -->
Конечно, `type=reset|submit` и у `button` есть

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <a href="#" aria-label="Ссылка на полноразмерное изображение">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +            aria-label="Ссылка на HTML Academy">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143)

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +            <a class="social-link" href="https://twitter.com/?lang=ru" aria-label="Ссылка на Twitter">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143), `Страница в Twitter`?

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +            <a class="social-link" href="https://www.facebook.com/" aria-label="Ссылка на Facebook">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143), `Страница в Facebook`?

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +            <a class="social-link" href="https://www.youtube.com/" aria-label="Ссылка на You Tube">
[143](https://github.com/htmlacademy-adaptive/1705973-pink-22/pull/4/files?file-filters%5B%5D=.html&file-filters%5B%5D=.jpg&file-filters%5B%5D=.svg#diff-ab0677ad3f964bb5353f01169c9a2e0d1c10e10dafd5867acb4bf8adb74d0199R143), `YouTube-канал`?

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +      </button>
Можно лучше. Например, обойтись одной кнопкой, просто подменять изображение внутри, `aria-label` и результат по клику

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +              <img src="img/youtube.svg" width="15" height="13" alt="You Tube">
Слитно пишется - `YouTube`

2021-04-09 21:26 UTC, mikhailmaclay commented on source/photos.html
> +        <svg class="page-footer__logo-icon" width="145" height="40" viewBox="0 0 145 40" fill="currentColor"
`-icon` тут лишнее, это ж логотип. То что ты его перекрашиваешь через `currentColor`, не делает его иконкой

2021-04-10 16:20 UTC, Belladonna26 commented on source/photos.html
> +          <cite class="photofeed__author">Анна</cite>
да в целом при смене типа блока, оберну в span

2021-04-13 04:48 UTC, mikhailmaclay approved these changes

2021-04-13 04:49 UTC, mikhailmaclay approved these changes

2021-04-13 16:01 UTC, merged