Переверстывает главную и форму и стилизует таблицу и филдсеты
htmlacademy-adaptive/1705973-pink-22 pull request #6
Opened 2021-04-21 14:41 UTC by Belladonna26

2021-04-23 07:25 UTC, mikhailmaclay requested changes

2021-04-23 07:25 UTC, mikhailmaclay commented on source/sass/blocks/fieldset.scss
> +}
Можно проще:
`
.fieldset__item:not(:last-child) {
    margin-bottom: 47px;
}
`

2021-04-23 07:25 UTC, mikhailmaclay commented on source/sass/blocks/fieldset.scss
> +  padding: 23px 20px;
Смысла добавлять вертикальные `padding` нет, все равно текст будет по центру

2021-04-23 07:25 UTC, mikhailmaclay commented on source/form.html
> +          <input class="info-input fieldset__field-data" type="text" name="surname" id="user-surname"
Не увидел стилей для `fieldset__field-data`, смысла в нем не вижу, да и странное имя для элемента, который представляет из себя поле ввода

2021-04-23 07:25 UTC, mikhailmaclay commented on source/form.html
> +          <label class="info-label" for="user-surname">Фамилия</label>
`info-label, info-input` все еще выглядят странно

2021-04-23 07:25 UTC, mikhailmaclay commented on source/sass/blocks/competition.scss
> +.competition__condition-wrapper {
Почему нельзя это засунуть в `.competition__condition?`

2021-04-23 07:25 UTC, mikhailmaclay commented on source/form.html
> +        <textarea class="fieldset__area" name="review" id="review-field">Можно прям в красках, не стесняясь в выражениях</textarea>
Не стоит через `fieldset` идти, лучше стилизуй через свой класс, а лучше используй универсальный класс для инпутов. Там выше у тебя есть инпуты, которые выглядят так же. Разве что размеры нужно будет через модификатор обозначить. Не забудь добавить `resize: none`

2021-04-23 07:25 UTC, mikhailmaclay commented on source/form.html
> +  <section class="modal modal_success">
А зачем такие модификаторы тут и выше?

2021-04-29 14:58 UTC, Belladonna26 commented on source/sass/blocks/fieldset.scss
> +  padding: 23px 20px;
в fieldset__area он прижимается к краям тогда, а вот в инпутах держится по центру

2021-04-29 19:43 UTC, mikhailmaclay requested changes
Нормально css не смог проверить, так как изменения прилетели из коммита, который должен быть в другой ветке. Выпиливай его, внеси правки по замечаниям и отпишись мне, я перепроверю

2021-04-29 19:43 UTC, mikhailmaclay commented on source/sass/blocks/top-background.scss
> +  background-repeat: no-repeat;
Уже есть в основном классе. Плюс ты используешь препроцессор, поэтому можно писать медиа-запрос прямо в наборе правил.
Зачем указываешь `screen`? Без него, кстати, тоже будет работать

2021-04-29 19:43 UTC, mikhailmaclay commented on source/sass/blocks/button.scss
> +  border: 2px solid $jungle-green;
Зачем?

2021-04-29 19:43 UTC, mikhailmaclay commented on source/sass/blocks/fieldset.scss
> +  box-sizing: border-box;
Зачем?

2021-04-29 19:43 UTC, mikhailmaclay commented on source/sass/blocks/fieldset.scss
> +.fieldset__title {
![image](https://user-images.githubusercontent.com/46678623/116607389-98b30b00-a93a-11eb-953f-c29f370efdec.png)
Дублирование разметки необходимо убрать. Постарайся решить эту задачу через один элемент

2021-04-29 19:43 UTC, mikhailmaclay commented on source/sass/blocks/fieldset.scss
> +.fieldset__area {
Мы же договорились стилизовать `textarea` через класс, который стилизует инпуты
![image](https://user-images.githubusercontent.com/46678623/116607674-f3e4fd80-a93a-11eb-9331-c1ad39dba5e2.png)

2021-04-29 19:43 UTC, mikhailmaclay commented on source/sass/blocks/info-input.scss
> +.info-input {
Давай просто `input`

2021-04-29 19:43 UTC, mikhailmaclay commented on source/form.html
> +        <textarea class="fieldset__area" name="review" id="review-field">Можно прям в красках, не стесняясь в выражениях</textarea>
`Можно прям в красках, не стесняясь в выражениях` это `placeholder`

2021-04-29 19:43 UTC, mikhailmaclay commented on source/form.html
> +      <div class="page-header__menu-buttons">
Баг
![image](https://user-images.githubusercontent.com/46678623/116608115-7b327100-a93b-11eb-9f70-36274be41b94.png)
![image](https://user-images.githubusercontent.com/46678623/116608174-92715e80-a93b-11eb-8368-3821e0c0dc81.png)

2021-04-29 19:43 UTC, mikhailmaclay commented on source/form.html
> +              <a class="main-navigation__link" href="index.html">Главная</a>
Баг
![image](https://user-images.githubusercontent.com/46678623/116608223-a1581100-a93b-11eb-9792-de2efe3b611c.png)

2021-05-01 14:56 UTC, merged